title: Digital post-its and chaotic notes
email: j.carselind[at]googlemail
description: >-
  A place to write down experiences, gather solutions that I come acrose
  as a software engineer and improve my technical writing as tech-lead.
baseurl: ""
url: ""
twitter_username: jcarselind
github_username:  joacar

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
