source "https://rubygems.org"
# https://pages.github.com/versions/
gem "jekyll", "~> 3.9.0"
gem "minima", "~> 2.5"
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", "~> 208", group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
